name: PukPuk
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.PukPuk

targets:
  App:
    type: application
    platform: iOS
    sources: [PukPuk]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.PukPuk.App
      INFOPLIST_FILE: PukPuk/Info.plist
      GENERATE_INFOPLIST_FILE: true
      base:
        TARGETED_DEVICE_FAMILY: "1"  # iPhone only
        SUPPORTED_INTERFACE_ORIENTATIONS: "UIInterfaceOrientationPortrait"  # Portrait only

  PukPuk-Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [PukPuk-Tests]
    dependencies:
      - target: App
    settings:
      base:
        INFOPLIST_FILE: PukPuk/Info.plist
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/App.app/App"
        BUNDLE_LOADER: "$(TEST_HOST)"

  PukPukIntentsExtension:
    type: app-extension
    platform: iOS
    sources: [PukPukIntentsExtension]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.PukPuk.AppIntentsExtension
      INFOPLIST_FILE: PukPukIntentsExtension/Info.plist
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: App
      
  PukPukIntentsExtensionUI:
    type: app-extension
    platform: iOS
    sources: [PukPukIntentsExtensionUI]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.PukPuk.AppIntentsExtensionUI
      INFOPLIST_FILE: PukPukIntentsExtensionUI/Info.plist
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: PukPukIntentsExtension

schemes:
  PukPuk:
    build:
      targets:
        App: all
        PukPuk-Tests: all
        PukPukIntentsExtension: all
        PukPukIntentsExtensionUI: all
    test:
      targets:
        - name: PukPuk-Tests
          gatherCoverageData: true
