name: PukPuk
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.PukPuk

targets:
  PukPuk:
    type: application
    platform: iOS
    sources: [PukPuk]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.PukPuk.PukPuk
      INFOPLIST_FILE: PukPuk/Info.plist
      GENERATE_INFOPLIST_FILE: true

  PukPuk-Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [PukPuk-Tests]
    dependencies:
      - target: PukPuk
    settings:
      base:
        INFOPLIST_FILE: PukPuk/Info.plist
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PukPuk.app/PukPuk"
        BUNDLE_LOADER: "$(TEST_HOST)"

  PukPukIntentsExtension:
    type: app-extension
    platform: iOS
    sources: [PukPukIntentsExtension]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.PukPuk.PukPukIntentsExtension
      INFOPLIST_FILE: PukPukIntentsExtension/Info.plist
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: PukPuk
      
  PukPukIntentsExtensionUI:
    type: app-extension
    platform: iOS
    sources: [PukPukIntentsExtensionUI]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.PukPuk.PukPukIntentsExtensionUI
      INFOPLIST_FILE: PukPukIntentsExtensionUI/Info.plist
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: PukPukIntentsExtension

schemes:
  PukPuk:
    build:
      targets:
        PukPuk: all
        PukPuk-Tests: all
        PukPukIntentsExtension: all
        PukPukIntentsExtensionUI: all
    test:
      targets:
        - name: PukPuk-Tests
          gatherCoverageData: true
