//
//  ResultDataSource.swift
//  PukPuk
//
//  Created by Sena Kristiawan on 15/08/24.
//

import Foundation

protocol ResultDataSourceProtocol {
    func getRecommendation(for classificationResult: ClassificationResult) -> RecommendationEntity
}

class ResultDataSource : ResultDataSourceProtocol {
    func getRecommendation(for classificationResult: ClassificationResult) -> RecommendationEntity {
        switch classificationResult {
        // Generated by GPT
        case .tired:
            return RecommendationEntity(
                cryType: "Tired",
                description: "Your baby is tired and may need to sleep. Try soothing them to sleep.",
                steps: [
                    "Dim the lights and reduce noise",
                    "Rock the baby gently or use a swing",
                    "Place the baby in their crib for a nap"
                ]
            )
        case .hungry:
            return RecommendationEntity(
                cryType: "Hunger",
                description: "Your baby seems hungry. Make sure to feed them in a calm environment.",
                steps: [
                    "Prepare a bottle or breastfeed",
                    "Ensure the baby is in a comfortable position",
                    "Feed the baby slowly and burp frequently"
                ]
            )
        case .belly_pain:
            return RecommendationEntity(
                cryType: "Belly Pain",
                description: "Your baby may have belly pain. Gently rub their belly to relieve discomfort.",
                steps: [
                    "Lay the baby on their back and move their legs in a bicycling motion",
                    "Gently massage the baby’s belly",
                    "Give the baby a warm bath to relax them"
                ]
            )
        case .discomfort:
            return RecommendationEntity(
                cryType: "Discomfort",
                description: "Your baby seems uncomfortable. Check if their clothes are too tight or if the environment is too hot or cold.",
                steps: [
                    "Check the baby's diaper and change if necessary",
                    "Ensure the baby is dressed appropriately for the weather",
                    "Adjust the room temperature to a comfortable level"
                ]
            )
        case .burping:
            return RecommendationEntity(
                cryType: "Burping",
                description: "Your baby might need to burp. Hold them upright and gently pat their back.",
                steps: [
                    "Hold the baby upright against your chest",
                    "Gently pat or rub the baby’s back",
                    "Try different burping positions if needed"
                ]
            )
        }
    }
}
