//
//  ResultDataSource.swift
//  PukPuk
//
//  Created by Sena Kristiawan on 15/08/24.
//

import Foundation

protocol ResultDataSourceProtocol {
    func getRecommendation(for classificationResult: ClassificationResult) -> RecommendationEntity
}

class ResultDataSource : ResultDataSourceProtocol {
    func getRecommendation(for classificationResult: ClassificationResult) -> RecommendationEntity {
        switch classificationResult {
        // Generated by GPT
        case .tired:
            return RecommendationEntity(
                cryType: "Tired",
                description: "Your baby might be tired, they could be ready for a nap or bedtime.",
                steps: [
                    RecommendationStepDetail(title: "Sleep your baby", desc: "Put your baby to sleep in a safe and cozy spot."),
                    RecommendationStepDetail(title: "Wrap Securely", desc: "Wrap your baby snugly to help them feel secure, but stop once they can roll onto their tummy (around 3-4 months)")
                ]
            )
        case .hungry:
            return RecommendationEntity(
                cryType: "Hunger",
                description: "Your baby might be hungry, they could be signaling it’s feeding time.",
                steps: [
                    RecommendationStepDetail(title: "Hunger Check", desc: "Offer the breast or bottle if your baby seems hungry."),
                    RecommendationStepDetail(title: "Comfort Sucking", desc: "Use a dummy if your baby just wants to suck for comfort."),
                    RecommendationStepDetail(title: "Self-Soothing", desc: "Help older babies find their fingers to self-soothe."),
                ]
            )
        case .belly_pain:
            return RecommendationEntity(
                cryType: "Belly Pain",
                description: "Your baby might be experiencing belly pain, they could be uncomfortable.",
                steps: [
                    RecommendationStepDetail(title: "Gentle Tummy Massage", desc: "Try gently massaging your baby's tummy in a clockwise direction to relieve discomfort."),
                    RecommendationStepDetail(title: "Hold for Comfort", desc: "Hold your baby close to provide comfort during belly pain."),
                    RecommendationStepDetail(title: "Warm Bath", desc: "A warm bath might help relax your baby's muscles and ease their discomfort."),
                    RecommendationStepDetail(title: "Consult a Professional", desc: "If the pain persists or you're concerned, check with a healthcare professional to ensure everything is okay."),
                    
                ]
            )
        case .discomfort:
            return RecommendationEntity(
                cryType: "Discomfort",
                description: "Your baby might be trying to tell you something isn’t right.",
                steps: [
                    RecommendationStepDetail(title: "Soothe Your Baby", desc: "Hold your baby close and gently pat or stroke their back."),
                    RecommendationStepDetail(title: "Temperature Check", desc: "Ensure your baby is not too hot or too cold, and adjust their clothing for comfort."),
                ]
            )
        case .burping:
            return RecommendationEntity(
                cryType: "Burping",
                description: "Your baby might need to burp and trying to release some trapped air.",
                steps: [
                    RecommendationStepDetail(title: "Burp After Feeding", desc: "If your baby swallows air during feeding, try burping them."),
                    RecommendationStepDetail(title: "Hold Upright", desc: "Gently hold your baby upright against your shoulder with a cloth to catch any spit-up."),
                    RecommendationStepDetail(title: "Rub Their Back", desc: "Support your baby with one hand and softly rub their back with the other. It's normal if a little milk comes up during burping—don’t worry, this is completely natural."),
                ]
            )
        }
    }
}
